#!/usr/bin/env bash
#   Copyright 2017 Otavio Rodolfo Piske
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

JAVA_VERSION=17

darwin=false
linux=false

# OS specific support.  $var _must_ be set to either true or false.
case "$(uname)" in
    Darwin*) darwin=true ;;
    Linux*) darwin=true ;;
esac


if ${darwin}; then
  if [ -z "${JAVA_HOME}" ] ; then
        export JAVA_HOME="$(brew --prefix openjdk@${JAVA_VERSION})"
        export PATH=$PATH:$JAVA_HOME/bin
        echo set
  fi
fi

# Installation paths
localDir="$(dirname $(readlink -f $0))"
installDir="$(dirname "${localDir}")"

if [[ ${installDir} == "." ]] ; then
	installDir=".."
fi

source "${installDir}/config/providence-collector.jvm.conf"

export PROVIDENCE_JVM_FLAGS="${PROVIDENCE_JVM_OTHER_OPTS} ${PROVIDENCE_JVM_MEM_OPTS}"

if [[  ${PROVIDENCE_DEBUG} == "y" ]] ; then
    PROVIDENCE_JVM_FLAGS="${PROVIDENCE_JVM_FLAGS} ${PROVIDENCE_DEBUG_ARGS}"
fi

mainClass="org.providence.main.ProvidenceCollectorMain"

classpath="$(echo "${installDir}"/bin/*providence-collector-*.jar)"
classpath="${classpath// /:}"

nice -n 15 java ${PROVIDENCE_JVM_FLAGS} -classpath "${classpath}" -Dorg.providence.home="${installDir}" \
    ${PROVIDENCE_JAVA_OPTS} "${mainClass}" "$@"
